Study
JudjinGM/PlaylistMaker pull request #3
Opened 2023-02-22 11:49 UTC by JudjinGM

Sending my sprint 9 work for code review before merge

2023-02-22 22:15 UTC, NoDopezzz requested changes

2023-02-22 22:15 UTC, kirillNay commented on app/src/main/res/layout/activity_main.xml
> +        android:textAppearance="@style/MainTitleText" />
✅ Отличное решение вынести специфичные атрибуты для текста в `textAppearance`!

2023-02-22 22:15 UTC, kirillNay commented on build.gradle
> +    id 'org.jetbrains.kotlin.android' version '1.8.20-Beta' apply false
Лучше стараться избегать обновления зависимостей в проекте, если жто не требует сама задача. Из-за этого могут случайно появится непредвиденные ошибки и артефакты при сборке и работе приложения

(Иногда Android Studio сама любит неожиданно обновлять версии, так что за этим стоит следить)

2023-02-22 22:15 UTC, kirillNay commented on app/src/main/res/values-en/strings.xml
> +    <string name="share_link">https://practicum.yandex.ru/android-developer/</string>
⏫  Значения `share_link` и `developer_email_address` не отличаются для разных языков. Чтобы их не приходилось дублировать в коде достаточно лишь одну версию этих строк в `values/strings.xml`

2023-02-22 22:15 UTC, kirillNay commented on app/src/main/res/values/styles.xml
> +        <item name="android:textColor">@color/white</item>
⚠️ Согласно дизайну заголовки на экранах приложения имеют немного другой шрифт - `ys_display_medium`

<img width="987" alt="image" src="https://user-images.githubusercontent.com/56832972/220730804-e7160834-97b8-44c2-adb2-7d3b08a66c6d.png">

2023-02-22 22:15 UTC, kirillNay commented on app/src/main/res/layout/activity_settings.xml
> +        android:layout_marginStart="@dimen/title_image_margin"
⏫  Атрибуты кнопки "Назад" тоже можно вынести в стили, чтобы легко переиспользовать ее на других экранах.
К этим аттрибутам можно отнести: `android:contentDescription`, `android:src` и `app:tint`

В дальнейшем, если дизайн кнопки изменится - поменяется ее цвет или сама иконка, то будет достаточно это изменить лишь в одном месте

2023-02-22 22:15 UTC, kirillNay commented on app/src/main/res/drawable/arrow_back_dark_mode.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
✅ Для изменения цвета иконок в зависимости от выбранной темы используешь изменение оттенка иконки. Очень хорошее решение!

⏫ В таком случае, можно удалить неиспользуемые `*_dark_mode` иконки из папки `res`, чтобы они не занимали лишнее место в ресурсах

2023-02-22 22:15 UTC, kirillNay commented on app/src/main/res/values/styles.xml
> +        <item name="android:textColor">@color/white</item>
Стоит обратить внимание на построенную иерархию текстовых стилей. Шрифт, объявленный в `MainTitleText` расходится с тем, что указан в дизайне из-за чего происходит также путаница и в дочерних стилях.

2023-02-22 22:15 UTC, NoDopezzz commented on app/src/main/res/values-night/styles.xml
> +     <style name="SwitchWithKnob">
⏫ На самом деле, свич не меняет свой стиль в зависимости от темы, он лишь меняет свой цвет в зависимости от своего состояния: включен или выключен. Подобное изменение цвета происходит программно и нам не нужно об этом беспокоиться.

Можно не беспокоиться над реализацией смены темы приложения сейчас, т.к. подобный функционал будет подробно разобран в **спринте 12**.

2023-02-23 17:42 UTC, JudjinGM commented on build.gradle
> +    id 'org.jetbrains.kotlin.android' version '1.8.20-Beta' apply false
к сожалению, я, по совету AS обновил, на данный момент еще не понимаю, как откатить обратно

2023-02-23 18:55 UTC, NoDopezzz commented on build.gradle
> +    id 'org.jetbrains.kotlin.android' version '1.8.20-Beta' apply false
Можно просто вернуть строку `id 'org.jetbrains.kotlin.android' version '1.7.21' apply false` отдельным коммитом. 

В принципе, ничего страшного с поднятием версии котлина до 1.8.20 не должно произойти. Так что можем оставить так)

2023-02-27 14:04 UTC, merged